"""Rendering human-facing views: the README index block and per-category pages.

All rendered values pass through Markdown escaping and plain-text reduction
so no title, tag or summary from a contributor document can break table
layout or inject active content into the README.
"""

from __future__ import annotations

from typing import TYPE_CHECKING
from urllib.parse import quote

from cyberkb.markdown import escape_inline
from cyberkb.textutil import plain_text, truncate

if TYPE_CHECKING:
    from collections.abc import Mapping, Sequence

    from cyberkb.library import Resource
    from cyberkb.taxonomy import Taxonomy

__all__ = [
    "README_END",
    "README_START",
    "render_category_page",
    "render_index_block",
    "splice_readme",
]

README_START = "<!-- BEGIN AUTO-INDEX -->"
README_END = "<!-- END AUTO-INDEX -->"
_MAX_TITLE_CELL = 70
_MAX_SUMMARY_CELL = 140


def _link(resource: Resource) -> str:
    title = escape_inline(truncate(plain_text(resource.front_matter.title), _MAX_TITLE_CELL))
    return f"[{title}]({quote(resource.path, safe='/._-')})"


def _group(resources: Sequence[Resource]) -> dict[str, list[Resource]]:
    grouped: dict[str, list[Resource]] = {}
    for resource in resources:
        grouped.setdefault(resource.category, []).append(resource)
    return grouped


def render_index_block(
    catalog: Mapping[str, object],
    resources: Sequence[Resource],
    taxonomy: Taxonomy,
) -> str:
    """Render the summary table that lives between the README AUTO-INDEX markers."""
    counts = catalog["counts"]
    assert isinstance(counts, dict)  # noqa: S101 -- catalog shape is guaranteed by build_catalog
    grouped = _group(resources)
    lines = [
        (
            f"> Catalog regenerated **{catalog['generated_at']}** | "
            f"**{counts['total']}** resources across "
            f"**{sum(1 for g in grouped.values() if g)}** categories. "
            "Machine-readable: [`index.json`](index.json) / [`index.yaml`](index.yaml)."
        ),
        "",
        "| Category | Count | Most recent additions |",
        "| --- | ---: | --- |",
    ]
    for cat in taxonomy.categories:
        subset = grouped.get(cat.id, [])
        if not subset:
            continue
        recent = sorted(
            subset, key=lambda r: (r.front_matter.added, r.front_matter.title), reverse=True
        )[:3]
        highlights = "; ".join(_link(r) for r in recent)
        name = escape_inline(cat.name)
        lines.append(f"| [{name}]({_category_page_path(cat.id)}) | {len(subset)} | {highlights} |")
    lines.append("")
    return "\n".join(lines).rstrip()


def _category_page_path(category_id: str) -> str:
    return f"library/{category_id}/README.md"


def splice_readme(readme_text: str, block: str) -> str:
    """Return ``readme_text`` with the AUTO-INDEX block replaced by ``block``.

    If the markers are absent the managed section is appended once; if only
    one marker is present the text is returned unchanged so a corrupted README
    is never silently rewritten.
    """
    section = f"{README_START}\n{block}\n{README_END}"
    start = readme_text.find(README_START)
    end = readme_text.find(README_END)
    if start == -1 and end == -1:
        base = readme_text.rstrip("\n")
        return f"{base}\n\n{section}\n" if base else f"{section}\n"
    if start == -1 or end == -1 or end < start:
        return readme_text
    return readme_text[:start] + section + readme_text[end + len(README_END) :]


def render_category_page(
    category_id: str, resources: Sequence[Resource], taxonomy: Taxonomy
) -> str:
    """Render a browsable ``library/<category>/README.md`` listing every resource."""
    category = taxonomy.category(category_id)
    subset = sorted(resources, key=lambda r: r.front_matter.title.casefold())
    cybok = ", ".join(f"{code} ({taxonomy.cybok[code]})" for code in category.cybok) or "--"
    nice = ", ".join(f"{code} ({taxonomy.nice[code]})" for code in category.nice) or "--"
    lines = [
        f"# {escape_inline(category.name)}",
        "",
        plain_text(category.description),
        "",
        f"- **CyBOK knowledge areas:** {escape_inline(cybok)}",
        f"- **NICE workforce categories:** {escape_inline(nice)}",
        f"- **Resources:** {len(subset)}",
        "",
        "> This page is generated by `cyberkb build`. Do not edit by hand.",
        "",
        "| Resource | Format | Lang | Tags | Summary |",
        "| --- | --- | --- | --- | --- |",
    ]
    for resource in subset:
        front_matter = resource.front_matter
        tags = ", ".join(escape_inline(t) for t in front_matter.tags) or "--"
        summary = (
            escape_inline(truncate(plain_text(front_matter.summary), _MAX_SUMMARY_CELL)) or "--"
        )
        lines.append(
            f"| {_link(resource)} | {front_matter.format} | {front_matter.language} "
            f"| {tags} | {summary} |",
        )
    lines.append("")
    return "\n".join(lines)
